name: Build Rust

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-22.04']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Rust
        if: ${{ hashFiles('Cargo.toml') != '' }}
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy, rustfmt
      - name: Cache rust
        if: ${{ hashFiles('Cargo.toml') != '' }}
        uses: Swatinem/rust-cache@v2
      - name: Test
        if: ${{ hashFiles('Cargo.toml') != '' }}
        run: cargo test
      - name: Build
        if: ${{ hashFiles('Cargo.toml') != '' }}
        run: cargo build --release
