name: Check all

on:
  - push
  - pull_request

jobs:
  check-all:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install system packages
        run: |
          sudo apt-get update && sudo apt-get install -y \
            linux-headers-$(uname -r)

      - name: Prepare CMake, compile_commands.json
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -S .
          cp build/compile_commands.json .

      - name: Check all
        uses: tsnlab/check@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
