name: Lint Rust

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Rust
        if: ${{ hashFiles('Cargo.toml') != '' }}
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy, rustfmt
      - name: Cargo fmt
        if: ${{ hashFiles('Cargo.toml') != '' }}
        uses: actions-rust-lang/rustfmt@v1
      - name: Cargo clippy
        if: ${{ hashFiles('Cargo.toml') != '' }}
        uses: giraffate/clippy-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
