name: Lint Python

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Flake8, pyright, mypy
        run: pip install flake8 flake8-import-order flake8-builtins pyright mypy
      - name: Install dependencies with poetry
        if: ${{ hashFiles('poetry.lock') != '' }}
        run: |
          pipx install poetry  # Install poetry
          poetry install  # Install dependencies with poetry
          echo "$(poetry env info --path)/bin" >> $GITHUB_PATH  # Set PATH variable
      - name: Linters
        uses: wearerequired/lint-action@v2
        with:
          flake8: true
          mypy: true
          mypy_args: --disable-error-code=import-untyped --check-untyped-defs
      - name: Pyright
        uses: jakebailey/pyright-action@v2
        with:
          warnings: true
